# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnoapp', '0002_auto_20160905_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcm_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
