# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnoapp', '0004_delete_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcm_id', models.CharField(blank=True, max_length=100)),
                ('fb_id', models.CharField(blank=True, max_length=100)),
                ('referral', models.BooleanField(default=False)),
                ('is_master', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='Master_Profile',
        ),
    ]
