# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnoapp', '0005_auto_20160912_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_profile',
            name='fb_id',
        ),
        migrations.RemoveField(
            model_name='master_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='fb_id',
        ),
    ]
