# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnoapp', '0006_auto_20160912_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_profile',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='master_profile',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='is_master',
        ),
    ]
